default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: Scheduler_development

production:
  <<: *default
  database: Scheduler_production
  username: Scheduler
  password: "<%= Rails.application.credentials.dig(:database, :password) %>"
