default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: SkafferBot_development

production:
  <<: *default
  database: SkafferBot_production
  username: SkafferBot
  password: "<%= Rails.application.credentials.mysql[:prod_password] %>"
