common: &default_settings
  license_key: <%= Rails.application.credentials.dig(:newrelic, :license_key) %>

  app_name: SkafferBot

  # Logging level for log/newrelic_agent.log
  log_level: info

development:
  <<: *default_settings

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
